# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_of_birth']},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-date_of_birth'], name='account_pro_date_of_797c80_idx'),
        ),
    ]
