# Generated by Django 5.0.6 on 2024-06-18 12:34

import furni.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creslo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=furni.helpers.SaveMediaFiles.category_img_path)),
                ('create_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=furni.helpers.SaveMediaFiles.product_img_path)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('$', 'USD'), ('UZS', "so'm")], default='$', max_length=10)),
                ('create_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=furni.helpers.SaveMediaFiles.category_img_path)),
                ('create_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=furni.helpers.SaveMediaFiles.category_img_path)),
                ('create_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
